apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-simple-app
  namespace: default
spec:
  type: Python
  mode: cluster
  image: wordcount-minio:latest
  mainApplicationFile: local:///opt/spark/input/wordcount-minio.py
  # deps:
  #   jars:
  #   - https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar
  #   - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.5
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.5.5
  sparkVersion: "3.5.5"
