apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-kafka
  namespace: default
spec:
  type: Python
  mode: cluster
  image: stream:latest
  mainApplicationFile: local:///opt/spark/input/kafka.py
  # deps:
  #   jars:
  #   - local:///opt/spark/jars/hadoop-aws.jar
  #   - local:///opt/spark/jars/aws-java-sdk-bundle.jar
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.5
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.5
  sparkVersion: "3.5.5"
