version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"   # Exposing MongoDB default port
    volumes:
      - mongo-data:/data/db
    networks:
      - spark_network

networks:
  spark_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
